### ISSUE TITLE
Add a metrics Dashboard to showcase

### ISSUE THREAD

**Issue by ANierbeck** [ANierbeck/Karaf-Vertx#19]

**Comment by anhldbk** [comment]
@ANierbeck How to access the Dashboard GUI?

**Comment by ANierbeck** [comment]
@anhldbk ... could be found in the sources ;) 
https://github.com/ANierbeck/Karaf-Vertx/commit/09ecf5e15c9e5cb4a4908c82cf18e795e44a32de#diff-bccf593ea77a28e62815e7e3a9c351acR105
it's /metrics

**Comment by anhldbk** [comment]
@ANierbeck Ah, I see. Thank you!

Btw, in your code of [Vertx-Http](https://github.com/ANierbeck/Karaf-Vertx/blob/master/Vertx-Http/src/main/java/de/nierbeck/example/vertx/http/VertxHttpServer.java#L37), we've got the following configuration:

```java
@ObjectClassDefinition(name = "Server Configuration")
@interface ServerConfig {
    int port() default 8080;
}
```

How to dynamically modify `port` via `bin/karaf` CLI? I tried to look for the port configuration but no luck.

```text
karaf@root()> config:list | grep port
```

**Comment by anhldbk** [comment]
@ANierbeck Never mind. I've solved it. Thank you so much for this repo.

**Comment by anhldbk** [comment]
@ANierbeck When I access `http://localhost:8080/metrics/index.html`, I've got an exception of:

```
Caused by: java.nio.file.FileSystemException: .vertx/file-cache-b968ce38-5354-4cf7-aa16-08bb5b982ab4/10.0/webroot/index.html: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:?]
	at java.nio.file.Files.copy(Files.java:3016) ~[?:?]
	at io.vertx.core.impl.FileResolver.unpackFromBundleURL(FileResolver.java:273) ~[?:?]
	... 48 more
```

The problem is `webroot` is not properly extracted to directory `.vertx/file-cache-b968ce38-5354-4cf7-aa16-08bb5b982ab4/10.0`. I solved by manually copying `webroot` to the directory.

Would you please tell me what wrong is?

**Comment by anhldbk** [comment]
In file [MetricsDashboard.java](https://github.com/ANierbeck/Karaf-Vertx/blob/master/Vertx-Microservices/Vertx-Microservice-MetricsDashboard/src/main/java/de/nierbeck/example/vertx/metrics/verticles/MetricsDashboard.java#L90), currently we have:
```java
// line 90
router.route("/*").handler(StaticHandler.create("webroot", this.getClass().getClassLoader()));
```

I modified to: 
```java
router.route("/*").handler(StaticHandler.create().setWebRoot("we‌​broot"));
```

@ANierbeck Should I make a PR against this issue?

**Comment by ANierbeck** [comment]
How do you use it? Inside an OSGi environment, in that case you should keep the classloader part :)

**Comment by anhldbk** [comment]
@ANierbeck I just entered `bin/karaf` and navigated to `/metrics`

```shell
Vertx-Microservices-Karaf/target/assembly on 🐳 v17.06.1-ce 
➜ bin/karaf
        __ __                  ____      
       / //_/____ __________ _/ __/      
      / ,<  / __ `/ ___/ __ `/ /_        
     / /| |/ /_/ / /  / /_/ / __/        
    /_/ |_|\__,_/_/   \__,_/_/         

  Apache Karaf (4.1.1)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

Configuration changed
karaf@root()> 

```
