### ISSUE TITLE
Error when importing the project into eclipse

### ISSUE THREAD

**Issue by iamparthak** [ANierbeck/Karaf-Vertx#22]
Hi 
I imported the project into eclipse but getting error in some projects like Vertx-Microservices-Karaf pom.xml. This is the error i am getting.
Plugin execution not covered by lifecycle configuration: org.apache.karaf.tooling:karaf-maven-plugin:4.0.7:assembly 
 (execution: default-assembly, phase: process-resources)

**Comment by ANierbeck** [comment]
There is no plugin for that, so please ignore it

**Comment by iamparthak** [comment]
so the project will work even without that plugin?

**Comment by ANierbeck** [comment]
yes ... those m2-eclipse plugins are not mandatory for eclipse, use a different IDE and you wouldn't even notice this.

**Comment by iamparthak** [comment]
Thanks ANierbeck
