### ISSUE TITLE
Add bundle extender for non OSGi Verticles

### ISSUE THREAD

**Issue by ANierbeck** [ANierbeck/Karaf-Vertx#27]
Right now it's mandatory to have AbstractVerticles or Verticles to be programmed in an OSGi way. 
Using DS service. 
It would be good to also register Verticles via Extender mechanism.

**Comment by anhldbk** [comment]
So this's implemented in module `Vertx-Extender`? Would you please tell me what the module's purpose?

**Comment by ANierbeck** [comment]
The purpose of this module is to act as a Extender for regular "bundles" where there is no direct registration of a Verticle service. Instead this extender scans bundles while being installed for containing Verticle classes. In that case those verticles are registered as services, from where on those vertircles can be handled as any other registered Verticle in the context of OSGi.
