### ISSUE TITLE
Vertx on karaf - How deployed Verticle?

### ISSUE THREAD

**Issue by cleberlira** [ANierbeck/Karaf-Vertx#35]
How to deploy Verticle (Vertx) on Karaf? I am using ServiceMix but not work.

The message look "Cannot deploy".

  vertx2.deployVerticle(VertxMqtt.class.getName(), ar -> {
       if (ar.succeeded()) {
            System.out.println`("Verticle deployed");
     } else {
          LOGGER.log(Level.SEVERE, "Cannot deploy " + verticle, ar.cause());
       }

    });
    }

**Comment by ANierbeck** [comment]
Leaving this for future questions: 
First of all make sure you have the depending vertx feature installed. 
Second register your verticle as Services, for example as declarative Service which implements a Verticle interface. That'll register the verticle automatically.
